### ISSUE TITLE
Pest Destroyer Rotates My View The Wrong Way

### ISSUE THREAD

**Issue by R7anW** [JellyLabScripts/FarmHelper#164]
when pest destroyer is triggered it kills the pest like normal but when i get warped back my rotation is wrong so i am facing towards the wrong side of my farm meaning that i get stuck anyone know how to fix this?

![pdc](https://github.com/JellyLabScripts/FarmHelper/assets/154217623/9f827147-0c5b-43e7-85e4-45db63e19a9a)
The Right Way I am meant to be facing 

![pdw](https://github.com/JellyLabScripts/FarmHelper/assets/154217623/9394ef4e-a468-4aca-9d81-3fb82ffbdaf6)
The way it faces me after warping back from pest destroyer trigger

**Comment by May2Beez** [comment]
You should join discord for better/faster help. Are you sure your spawnpoint is set properly? It should be facing shrooms and macro finds the rotation based on current rotation before running/resuming macro

**Comment by R7anW** [comment]
> You should join discord for better/faster help. Are you sure your spawnpoint is set properly? It should be facing shrooms and macro finds the rotation based on current rotation before running/resuming macro

yeah ill join 
well normally warping back without the pest destroyer works fine so im pretty sure that my spawnpoint is ok its just for the pest destroyer

**Comment by May2Beez** [comment]
> > You should join discord for better/faster help. Are you sure your spawnpoint is set properly? It should be facing shrooms and macro finds the rotation based on current rotation before running/resuming macro
> 
> yeah ill join well normally warping back without the pest destroyer works fine so im pretty sure that my spawnpoint is ok its just for the pest destroyer

Make sure to record the issue and send it in mod-support channel. We will try to find the issue

**Comment by R7anW** [comment]
> > > You should join discord for better/faster help. Are you sure your spawnpoint is set properly? It should be facing shrooms and macro finds the rotation based on current rotation before running/resuming macro
> > 
> > 
> > yeah ill join well normally warping back without the pest destroyer works fine so im pretty sure that my spawnpoint is ok its just for the pest destroyer
> 
> Make sure to record the issue and send it in mod-support channel. We will try to find the issue

ok will do thanks

**Comment by R7anW** [comment]
> > > You should join discord for better/faster help. Are you sure your spawnpoint is set properly? It should be facing shrooms and macro finds the rotation based on current rotation before running/resuming macro
> > 
> > 
> > yeah ill join well normally warping back without the pest destroyer works fine so im pretty sure that my spawnpoint is ok its just for the pest destroyer
> 
> Make sure to record the issue and send it in mod-support channel. We will try to find the issue

could you also send the discord link

**Comment by May2Beez** [comment]
> > > > You should join discord for better/faster help. Are you sure your spawnpoint is set properly? It should be facing shrooms and macro finds the rotation based on current rotation before running/resuming macro
> > > 
> > > 
> > > yeah ill join well normally warping back without the pest destroyer works fine so im pretty sure that my spawnpoint is ok its just for the pest destroyer
> > 
> > 
> > Make sure to record the issue and send it in mod-support channel. We will try to find the issue
> 
> could you also send the discord link

https://discord.gg/jellylab
