### ISSUE TITLE
auto repellent has some bugs, one of which destroys crops and then farms

### ISSUE THREAD

**Issue by kakapepean** [JellyLabScripts/FarmHelper#174]

**Comment by kakapepean** [comment]
crops get fully destroyed by repellent in hand

**Comment by XaineDev** [comment]
please record a clip of this happening and reply to the issue with it

**Comment by kakapepean** [comment]
i dont have a clipping software

**Comment by kakapepean** [comment]
some crops get fully destroyed by repellent in hand and then it switches to farming tool

**Comment by Nekiplay** [comment]
> i dont have a clipping software

download clipping software

**Comment by onixiya1337** [comment]
Don't use /neurename.
