### ISSUE TITLE
MacOS mouse vanish glitch

### ISSUE THREAD

**Issue by le1jurv** [JellyLabScripts/FarmHelper#180]
When using this on MacOS, the mouse vanishes, even in menus. Fixed by restarting the game, however it is very irritating.
Steps to reproduce:
Install it on Mac.
try to macro
watch your mouse permanently vanish

**Comment by May2Beez** [comment]
That's the issue of operating system, we can't do much about it. It is because of mouse ungrab. On MacOS you can't use it, if you want to macro. You will need to change the window by alt tabbing (the equivalent of alt on MacOS is Option iirc)
