### ISSUE TITLE
Visitor Macro

### ISSUE THREAD

**Issue by Snz1e** [JellyLabScripts/FarmHelper#183]
Please Make your bot Detect Dedication 4 , Overgrown grass and green bandana 

i had the visitor macro on and set the common to "profit only" and i dropped a Green Bandana but the Bot Denied it Becouse it wasnt profit. Please Fix

**Comment by splatboydev** [comment]
guess that means it wasn't profit 🙄

**Comment by onixiya1337** [comment]
The items' cost could've been outside the threshold limit.
