### ISSUE TITLE
Too much pest notifications

### ISSUE THREAD

**Issue by isabellaloves** [JellyLabScripts/FarmHelper#191]
I get a notification when there are 3 pests on the garden, even though it only starts reducing fortune at 4. Ideally, I would also like an option to set the threshold to like 5 or 6, because the reduction from 4 pests is barely noticeable, and even 5 isn't too terrible.

Also, every time the pest count goes down (because I kill a pest or one jumps off into the void), it sends a notification again if the pest count is still 3 or above.

**Comment by May2Beez** [comment]
You can set your threshold in the settings. The lowering pest count is just a small bug, it's not on the current todo fix list

**Comment by isabellaloves** [comment]
Ah, I had to enable Pests Destroyer to change the threshold, then I turned it back off and it applies to the notification too. Thanks. It should probably be changeable without Pests Destroyer enabled.
