### ISSUE TITLE
"Farm manually" when stopping and restarting after server restart

### ISSUE THREAD

**Issue by isabellaloves** [JellyLabScripts/FarmHelper#192]
1. Wait for server restart
2. Farm Helper successfully evacuates and comes back
3. Stop the macro manually
4. Start the macro again

Now I get this message:

> Farm Helper » Farm manually and DO NOT restart the macro too soon! The staff might still be spectating you for a while!

There was no macro check, only server restart.

**Comment by onixiya1337** [comment]
Fixed.
