### ISSUE TITLE
Pingless cactus incompatible with SkyHanni BPS meter

### ISSUE THREAD

**Issue by isabellaloves** [JellyLabScripts/FarmHelper#193]
If I use pingless cactus, SkyHanni BPS meter doesn't work. It doesn't detect that I'm farming. Only the garden milestone progress goes up with cultivating.

**Comment by onixiya1337** [comment]
This is how SkyHanni handles farming, nothing we can do about it.

**Comment by isabellaloves** [comment]
Hmm, sad. I doubt they are going to make a fix on their end to accomodate feature that is only present in a macro mod.

**Comment by isabellaloves** [comment]
I've found that changing the injection point of Farm Helper's mixin from `HEAD` to `TAIL` seems to fix the issue, and I can still break two rows of cactus at once.

**Comment by onixiya1337** [comment]
You've just proved me wrong. Thanks for finding the issue. We'll fix it soon.
