### ISSUE TITLE
Evacuation says "You are during staff check"

### ISSUE THREAD

**Issue by isabellaloves** [JellyLabScripts/FarmHelper#207]
When an evacuation happens due to a server restart, while in the Hub, the on-screen text displays some things like "You are during staff check / Press [key] to disable the macro / Do not leave, react". Although if I just ignore it, it goes back to the Garden and resumes farming just fine. So just a minor visual thing but probably worth fixing.

**Comment by onixiya1337** [comment]
Fixed.
