### ISSUE TITLE
the farmhelper bot.jar aint workin propperly

### ISSUE THREAD

**Issue by xireno** [JellyLabScripts/FarmHelper#25]
It isn't responding on the bot and keeps sending errors when i try to open the .jar file

**Comment by Jelly298** [comment]
What errors?

**Comment by nekiak** [comment]
> It isn't responding on the bot and keeps sending errors when i try to open the .jar file

Make a thread in [#🛠mod-support](https://discord.com/channels/997464259170680923/1022816363259105301) and try to be as specific as possible. Make sure to filter the threads using the search feature and see if anyone else has had the same problem as you.
