### ISSUE TITLE
staff check

### ISSUE THREAD

**Issue by ImVexi** [JellyLabScripts/FarmHelper#28]
staff checking for no reason. i keep getting staffchecked every 1-10mins and it wont stop.
![image](https://user-images.githubusercontent.com/128877896/233737834-42964b81-6dc2-4170-9e29-b67f52f3a527.png)

I'm not lagging cause I capped fps and my network is fine on every thing.

**Comment by CatalizCS** [comment]
![image](https://user-images.githubusercontent.com/36947924/233766592-e1f41052-eb95-4c28-a6a7-1d07bff64995.png)
Join the discord to receive the earliest information <3
