### ISSUE TITLE
Macro stuck at the end of a row (layered mode)

### ISSUE THREAD

**Issue by Gui6983** [JellyLabScripts/FarmHelper#32]

**Comment by Gui6983** [comment]
Please, fix this as soon as possible
If I get macro checked I am done

**Comment by sdjfoais** [comment]
Join the discord server: [https://discord.gg/6mSHC2Xd9y](url)
Also, send a screenshot of what the ends of your rows look like.

**Comment by Gui6983** [comment]
![2023-04-28_14 08 32](https://user-images.githubusercontent.com/132018941/235156175-7bc1a294-15ba-4d44-a2c6-fcf3af4e6104.png)
![2023-04-28_14 08 35](https://user-images.githubusercontent.com/132018941/235156181-065d1fea-a9c7-4e61-9187-12140856c537.png)
![2023-04-28_14 08 38](https://user-images.githubusercontent.com/132018941/235156183-3a2e093b-f911-4faf-8001-24d4f0b5993c.png)
![2023-04-28_14 08 33](https://user-images.githubusercontent.com/132018941/235156185-b38d5629-fda6-4434-affe-fbe79fa06f71.png)
![2023-04-28_14 08 36](https://user-images.githubusercontent.com/132018941/235156188-9b9668c0-b1e5-4d84-a8ff-e4e2a3cebfd9.png)

**Comment by Gui6983** [comment]
it just keep walking to right and left (speed 100). If I increase speed this bug can be avoided but I won't get all crops

**Comment by May2Beez** [comment]
Download the preview version from github's action tab, the problem might be solved there.

**Comment by sdjfoais** [comment]
You can also try making the part where you go forward 2 blocks wide instead of one
But tbh look into making a vertical farm since the new tools don't take that long to use and build any farm

**Comment by Emzudemil** [comment]
> Download the preview version from github's action tab, the problem might be solved there.
For me its fixed there

**Comment by Gui6983** [comment]
Alright, ty guys🫶

**Comment by Gui6983** [comment]
@May2Beez 
I am here just to notice you that the previous version also has the same bug

**Comment by May2Beez** [comment]
Old issue, fixed
