### ISSUE TITLE
Teleport Pads are disabled in Garden - Proposal here.

### ISSUE THREAD

**Issue by fer4ak** [JellyLabScripts/FarmHelper#38]
Hi,

Great project. 

As teleport pads were disabled in the Garden last night may you insert an 'if' string where the character will use '/warp garden' and start over after there isn't any movement for more than 2 seconds?

Something like this:

if (!mc.field_71439_g.field_70123_F && !mc.field_71439_g.field_70124_G && !mc.field_71439_g.field_70122_E) {
                Minecraft.getMinecraft().player.sendChatMessage("/warp garden");
            } 

Looking forward to your opinion.

Best Regards,
fer4ak

**Comment by wtfismyname69420** [comment]
This issue has been fixed in the latest preview version. Please join the discord and see the mod-support channel to get more information.

**Comment by May2Beez** [comment]
Old issue, rewarp is implemented now
