### ISSUE TITLE
Cocoa RG macro not being used when selected?

### ISSUE THREAD

**Issue by N0body42** [JellyLabScripts/FarmHelper#50]
I checked the CocoaBeanMacro.java and the CocoaBeanRGMacro.java.

The RG version has the pitch set to 90 whereas the regular macro has it set to 70.

No matter which option I select in the GUI menu it always sets the pitch to 70 which leads me to believe that it loads the regular macro even when the "RG" version is selected.

**Comment by May2Beez** [comment]
Fixed
