### ISSUE TITLE
Lily Pads cause anti-stuck to trigger on cane farms

### ISSUE THREAD

**Issue by tac-owo** [JellyLabScripts/FarmHelper#52]
How to Reproduce:

Step 1: Build 3 rows of cane. 
Step 2: For the transition in between the 2nd (backward) and 3rd (forward) rows, use a lily pad
Step 3: enable the script, and watch as you get stuck transferring over the lily pad

Only happens when the script is walking backwards over a lily pad, has no problems when just holding left.

**Comment by CatalizCS** [comment]
![image](https://github.com/JellyLabScripts/FarmHelper/assets/36947924/aef9eca5-fdf4-4814-aff4-1b95e3723984)
https://discord.gg/jellylab come discord for more infomation

**Comment by May2Beez** [comment]
Default sugar cane doesn't contain the lily pads, a niche and rare problem. Maybe we will fix it some day
