### ISSUE TITLE
How to fix these errors ?

### ISSUE THREAD

**Issue by J4kcio** [JellyLabScripts/FarmHelper#99]
Hi, I have two problems, the first is that after reaching the end of the farm and teleporting to the beginning where /sethome is set it stops farming for me. The second one is that after disconnecting from the server and rejoining (automatically) and entering skyblock I am at the beginning of the farm where /sethome is set, but nothing happens, no script works only standing still. How to fix this?

**Comment by J4kcio** [comment]
the first problem happens occasionally

**Comment by onixiya1337** [comment]
Send a video of your issue in #mod-support on our Discord server.
